INSERT INTO "products" ("name",
                        "description",
                        "price",
                        "picture_url",
                        "product_type_id",
                        "brand",
                        "quantity_in_stock")
VALUES ('Angular Speedster Board 2000',
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.',
        200,
        '/images/products/sb-ang1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boards'),
        'Angular',
        82),
       ('Green Angular Board 3000',
        'Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.',
        150,
        '/images/products/sb-ang2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boards'),
        'Angular',
        75),
       ('Core Board Speed Rush 3',
        'Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.',
        180,
        '/images/products/sb-core1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boards'),
        'NetCore',
        3),
       ('Net Core Super Board',
        'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.',
        300,
        '/images/products/sb-core2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boards'),
        'NetCore',
        52),
       ('React Board Super Whizzy Fast',
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.',
        250,
        '/images/products/sb-react1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boards'),
        'React',
        97),
       ('Typescript Entry Board',
        'Aenean nec lorem. In porttitor. Donec laoreet nonummy augue.',
        120,
        '/images/products/sb-ts1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boards'),
        'Typescript',
        37),
       ('Core Blue Hat',
        'Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.',
        10,
        '/images/products/hat-core1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Hats'),
        'NetCore',
        32),
       ('Green React Woolen Hat',
        'Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.',
        8,
        '/images/products/hat-react1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Hats'),
        'React',
        6),
       ('Purple React Woolen Hat',
        'Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.',
        15,
        '/images/products/hat-react2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Hats'),
        'React',
        17),
       ('Blue Code Gloves',
        'Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.',
        18,
        '/images/products/glove-code1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Gloves'),
        'VS Code',
        74),
       ('Green Code Gloves',
        'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.',
        15,
        '/images/products/glove-code2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Gloves'),
        'VS Code',
        19),
       ('Purple React Gloves',
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa.',
        16,
        '/images/products/glove-react1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Gloves'),
        'React',
        77),
       ('Green React Gloves',
        'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.',
        14,
        '/images/products/glove-react2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Gloves'),
        'React',
        45),
       ('Redis Red Boots',
        'Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.',
        250,
        '/images/products/boot-redis1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boots'),
        'Redis',
        49),
       ('Core Red Boots',
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.',
        189.99,
        '/images/products/boot-core2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boots'),
        'NetCore',
        28),
       ('Core Purple Boots',
        'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.',
        199.99,
        '/images/products/boot-core1.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boots'),
        'NetCore',
        69),
       ('Angular Purple Boots',
        'Aenean nec lorem. In porttitor. Donec laoreet nonummy augue.',
        150,
        '/images/products/boot-ang2.png',
        (SELECT "id" FROM "product_types" WHERE "name" = 'Boots'),
        'Angular',
        35),
       ('Angular Blue Boots',
        'Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.',
        180,
        '/images/products/boot-ang1.png', (SELECT "id" FROM "product_types" WHERE "name" = 'Boots'), 'Angular',
        27);
